"""
JSON-LD structured data extractor + validator.

Fetches a public URL, extracts all <script type="application/ld+json"> blocks,
parses them, and runs basic Schema.org validation (required fields per type).

Inspired by next-seo schema coverage. Validates the same high-value types
generated by tools.generators.
"""

from __future__ import annotations

import json
import logging
import re
from typing import Any

import requests

from modules.seo_suite.security import validate_public_url
from modules.seo_suite._common import ToolFetchError, fetch_html, safe_error

logger = logging.getLogger(__name__)

# Required-field map per @type. Used for "missing required field" warnings.
# Keys are Schema.org @type values (case-sensitive). Values are field names.
REQUIRED_FIELDS: dict[str, list[str]] = {
    "Article": ["headline", "author", "datePublished"],
    "NewsArticle": ["headline", "author", "datePublished"],
    "BlogPosting": ["headline", "author", "datePublished"],
    "Product": ["name"],
    "FAQPage": ["mainEntity"],
    "BreadcrumbList": ["itemListElement"],
    "LocalBusiness": ["name", "address"],
    "Organization": ["name", "url"],
    "Person": ["name"],
    "VideoObject": ["name", "description", "thumbnailUrl", "uploadDate"],
    "Event": ["name", "startDate", "location"],
    "HowTo": ["name", "step"],
    "Recipe": ["name", "image", "recipeIngredient", "recipeInstructions"],
    "JobPosting": ["title", "description", "datePosted", "hiringOrganization", "jobLocation"],
    "Course": ["name", "description", "provider"],
    "Review": ["itemReviewed", "reviewRating", "author"],
    "SoftwareApplication": ["name", "operatingSystem", "applicationCategory"],
    "WebPage": ["name"],
    "WebSite": ["name", "url"],
}

# Recognized known types — anything not in this set gets an informational note.
KNOWN_TYPES = set(REQUIRED_FIELDS.keys()) | {
    "ItemList",
    "Question",
    "Answer",
    "Offer",
    "AggregateRating",
    "Rating",
    "ImageObject",
    "Place",
    "PostalAddress",
    "HowToStep",
    "HowToSupply",
    "HowToTool",
    "ListItem",
    "MonetaryAmount",
    "QuantitativeValue",
    "NutritionInformation",
    "Brand",
    "Thing",
}

_SCRIPT_RE = re.compile(
    r"<script\b[^>]*type\s*=\s*[\"']application/ld\+json[\"'][^>]*>(.*?)</script\s*>",
    re.IGNORECASE | re.DOTALL,
)


def _validate_object(obj: Any, path: str = "$") -> list[dict[str, str]]:
    """Recursively validate a JSON-LD object. Returns a list of issues."""
    issues: list[dict[str, str]] = []

    if isinstance(obj, list):
        for i, item in enumerate(obj):
            issues.extend(_validate_object(item, f"{path}[{i}]"))
        return issues

    if not isinstance(obj, dict):
        return issues

    # @context check — only required at the root (path == "$")
    if path == "$" and "@context" not in obj:
        issues.append(
            {
                "level": "error",
                "path": path,
                "message": "Missing @context (should be https://schema.org)",
            }
        )
    elif path == "$":
        ctx = obj.get("@context", "")
        if isinstance(ctx, str) and "schema.org" not in ctx.lower():
            issues.append(
                {
                    "level": "warning",
                    "path": path,
                    "message": f"@context is '{ctx}', expected schema.org",
                }
            )

    # A root {"@context": ..., "@graph": [...]} wrapper (Yoast/RankMath style)
    # is valid without an @type of its own — the entities live inside @graph.
    has_graph = isinstance(obj.get("@graph"), list)

    at_type = obj.get("@type")
    if not at_type:
        # Nested objects without @type are common (e.g. plain author strings), only warn at root
        if path == "$" and not has_graph:
            issues.append(
                {
                    "level": "error",
                    "path": path,
                    "message": "Missing @type",
                }
            )
    else:
        # Normalize to list — @type can be a string or list
        types = at_type if isinstance(at_type, list) else [at_type]
        for t in types:
            if not isinstance(t, str):
                continue
            if t not in KNOWN_TYPES:
                issues.append(
                    {
                        "level": "info",
                        "path": path,
                        "message": f"Unrecognized @type '{t}' (not validated)",
                    }
                )
                continue
            required = REQUIRED_FIELDS.get(t, [])
            for field in required:
                if field not in obj or obj.get(field) in (None, "", []):
                    issues.append(
                        {
                            "level": "error",
                            "path": path,
                            "message": f"{t}: missing required field '{field}'",
                        }
                    )

    # Recurse into all dict/list values. @-keys are metadata and are skipped,
    # EXCEPT @graph — it holds the actual entities and must be validated.
    for key, val in obj.items():
        if key.startswith("@") and key != "@graph":
            continue
        if isinstance(val, dict | list):
            issues.extend(_validate_object(val, f"{path}.{key}"))

    return issues


def _extract_top_types(parsed: Any) -> list[str]:
    """Return the @type(s) at the root of a parsed JSON-LD block."""
    if isinstance(parsed, list):
        out: list[str] = []
        for item in parsed:
            out.extend(_extract_top_types(item))
        return out
    if isinstance(parsed, dict):
        # @graph wraps multiple entities
        if "@graph" in parsed and isinstance(parsed["@graph"], list):
            return _extract_top_types(parsed["@graph"])
        t = parsed.get("@type")
        if isinstance(t, list):
            return [x for x in t if isinstance(x, str)]
        if isinstance(t, str):
            return [t]
    return []


def validate_url(url: str, timeout: int = 8) -> dict[str, Any]:
    """
    Fetch URL, extract JSON-LD blocks, parse, validate. Returns structured report.
    """
    try:
        url = validate_public_url(url)
    except ValueError as e:
        return {"ok": False, "error": str(e)}

    try:
        resp = fetch_html(
            url,
            timeout=timeout,
            headers={
                "User-Agent": "Mozilla/5.0 (compatible; SEO-Suite/2.0; +https://seo-suite.local)"
            },
        )
    except (requests.RequestException, OSError, ValueError, ToolFetchError) as e:
        logger.warning("schema_validator fetch failed for %s: %s", url, e)
        return {"ok": False, "error": safe_error(e)}

    if resp.status_code >= 400:
        return {"ok": False, "error": f"HTTP {resp.status_code} from {url}"}

    html = resp.text or ""
    matches = _SCRIPT_RE.findall(html)

    blocks: list[dict[str, Any]] = []
    all_types: list[str] = []
    summary_errors = 0
    summary_warnings = 0

    for raw in matches:
        block_info: dict[str, Any] = {
            "raw": raw.strip(),
            "valid_json": False,
            "types": [],
            "issues": [],
            "parsed": None,
        }
        try:
            parsed = json.loads(raw)
            block_info["valid_json"] = True
            block_info["parsed"] = parsed
            block_info["types"] = _extract_top_types(parsed)
            all_types.extend(block_info["types"])
            issues = _validate_object(parsed)
            block_info["issues"] = issues
            summary_errors += sum(1 for i in issues if i["level"] == "error")
            summary_warnings += sum(1 for i in issues if i["level"] == "warning")
        except json.JSONDecodeError as e:
            block_info["issues"] = [
                {
                    "level": "error",
                    "path": "$",
                    "message": f"Invalid JSON: {e.msg} (line {e.lineno}, col {e.colno})",
                }
            ]
            summary_errors += 1
        blocks.append(block_info)

    # Recommendations — types Google highlights but were not found
    high_value_types = {
        "Article",
        "Product",
        "BreadcrumbList",
        "FAQPage",
        "Organization",
        "WebSite",
        "VideoObject",
    }
    found_set = set(all_types)
    recommendations = sorted(high_value_types - found_set)

    return {
        "ok": True,
        "url": url,
        "block_count": len(blocks),
        "types_found": sorted(set(all_types)),
        "blocks": blocks,
        "summary": {
            "errors": summary_errors,
            "warnings": summary_warnings,
        },
        "recommendations": recommendations,
    }
